name: Deploy Flask Application with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t dujiangjiang1/flask-app:latest

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: |
          docker push dujiangjiang1/flask-app:latest
